language: node_js
node_js:
  - "20.3.1"
dist:
  - "xenial"
os:
  - "linux"

addons:
  apt:
    sources:
      - ppa:ubuntu-toolchain-r/test
    packages:
      - g++-11

env:
  global:
    - CXX=g++-11
    - GH_REF: github.com/hook/champions.git

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy
